version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: investment-postgres
    environment:
      POSTGRES_DB: investment_engine
      POSTGRES_USER: invest_user
      POSTGRES_PASSWORD: invest_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invest_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: investment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: investment-app
    ports:
      - "8050:8050"
      - "8765:8765"
    environment:
      DATABASE_URL: postgresql://invest_user:invest_pass@postgres:5432/investment_engine
      REDIS_URL: redis://redis:6379/0
      APP_ENV: production
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: investment-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
